
scala:
  - 2.11.12
  - 2.12.11
  - 2.13.1

language: scala
script: >
  sbt ++$TRAVIS_SCALA_VERSION check coverage test sql_formatterJVM/coverageReport

jdk:
  - openjdk8
  - openjdk11

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier
